### ISSUE TITLE
README should provide instructions on use

### ISSUE THREAD

**Issue by OldhamMade** [akirak/conventional-commit.el#2]
Hi! Love the project, it's so useful to have tools like this which provide consistency across projects and teams.

It would be wonderful if the README had a bit more information on use; how to trigger the plugin, integrations with tools like Company-Mode/Corfu, etc. for Emacs users who are new to the editor or who don't do much Elisp development.

Thanks!

**Comment by akirak** [comment]
Hello, thank you for your interest, but this package requires a redesign.

The reason is because it would be better to integrate the package with external tools. See #1 for details. I have not clearly defined the workflow, but it would become a completely different package.

The instruction is already defined in README. You only have to add `conventional-commit-setup` to `git-commit-mode-hook`.
